### ISSUE TITLE
Como puxar boleto específico

### ISSUE THREAD

**Issue by rafacrt** [loja5combr/Segunda-via-Itau-Shopline-PHP#1]
Li o manual do itaú e o script de vocês, é possível puxar os boletos via cnpj e funciona bem

Porém aparecem TODOS os boletos emitidos para aquele cnpj especificado

Como fazer para aparecer um boleto especifico?

**Comment by loja5combr** [comment]
Ola, infelizmente o sistema deles não tem opção de especificar o boleto, apenas listagem geral de acordo o CPF/CNPJ do pagador.

https://vdocuments.site/2via-listagem-de-tftulos-unix.html
